#!/usr/bin/env bash
#
# Regenerate darwin/kinetic_player/Package.swift from both manifests.
# sharedDarwinSource: one SPM package for iOS + macOS.
#
# Usage:
#   bash darwin/scripts/sgplayer/generate_package_swift.sh
#   bash darwin/scripts/sgplayer/generate_package_swift.sh ios|macos   # ignored; regenerates unified file

set -euo pipefail

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "${SCRIPT_DIR}/_common.sh"

# Init with ios only to populate DARWIN_DIR / PLUGIN_ROOT paths.
kinetic_sgplayer_init "ios"

PACKAGE_SWIFT="${DARWIN_DIR}/kinetic_player/Package.swift"
MANIFEST_IOS="${DARWIN_DIR}/sgplayer/manifest.ios.json"
MANIFEST_MACOS="${DARWIN_DIR}/sgplayer/manifest.macos.json"

[[ -f "${MANIFEST_IOS}" ]] || sgplayer_fail "Missing ${MANIFEST_IOS}"
[[ -f "${MANIFEST_MACOS}" ]] || sgplayer_fail "Missing ${MANIFEST_MACOS}"

python3 - "${MANIFEST_IOS}" "${MANIFEST_MACOS}" "${PACKAGE_SWIFT}" <<'PY'
import json
import pathlib
import sys

def load_remote(path: pathlib.Path, label: str) -> tuple[str, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    url = (data.get("download_url") or "").strip()
    sha = (data.get("sha256") or "").strip().lower()
    if sha.startswith("sha256:"):
        sha = sha[len("sha256:") :]
    if not url:
        raise SystemExit(f"download_url is empty in {label}")
    if not sha or len(sha) != 64:
        raise SystemExit(f"sha256 must be a 64-char hex digest in {label}")
    return url, sha

ios_manifest, macos_manifest, package_path_s = sys.argv[1], sys.argv[2], sys.argv[3]
ios_url, ios_sha = load_remote(pathlib.Path(ios_manifest), "darwin/sgplayer/manifest.ios.json")
macos_url, macos_sha = load_remote(pathlib.Path(macos_manifest), "darwin/sgplayer/manifest.macos.json")
package_path = pathlib.Path(package_path_s)

generator = "darwin/scripts/sgplayer/generate_package_swift.sh"

content = f'''// swift-tools-version: 5.9
//
// Generated by {generator} — do not edit by hand.
// Source of truth: darwin/sgplayer/manifest.ios.json + manifest.macos.json

import PackageDescription

let package = Package(
    name: "kinetic_player",
    platforms: [
        .iOS(.v13),
        .macOS(.v11),
    ],
    products: [
        .library(name: "kinetic-player", targets: ["kinetic_player"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .binaryTarget(
            name: "SGPlayer_iOS",
            url: "{ios_url}",
            checksum: "{ios_sha}"
        ),
        .binaryTarget(
            name: "SGPlayer_macOS",
            url: "{macos_url}",
            checksum: "{macos_sha}"
        ),
        .target(
            name: "SgNativePlayerBridge",
            dependencies: [
                .target(name: "SGPlayer_iOS", condition: .when(platforms: [.iOS])),
                .target(name: "SGPlayer_macOS", condition: .when(platforms: [.macOS])),
            ],
            path: "Sources/SgNativePlayerBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedLibrary("iconv"),
                .linkedLibrary("bz2"),
                .linkedLibrary("z"),
            ]
        ),
        // SgPlayerKit Swift sources live under Sources/SgPlayerKit but must compile in the
        // main plugin target: intermediate SPM targets do not receive Flutter / FlutterMacOS
        // framework search paths from Flutter's Xcode integration.
        .target(
            name: "kinetic_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "SgNativePlayerBridge",
            ],
            path: "Sources",
            exclude: ["SgNativePlayerBridge"]
        ),
    ]
)
'''

package_path.parent.mkdir(parents=True, exist_ok=True)
package_path.write_text(content, encoding="utf-8")
print(f"[generate_package_swift] Wrote {package_path}")
print(f"[generate_package_swift] ios url={ios_url} checksum={ios_sha}")
print(f"[generate_package_swift] macos url={macos_url} checksum={macos_sha}")
PY
