#!/usr/bin/env bash
#
# Regenerate {ios|macos}/kinetic_player/Package.swift from darwin/sgplayer/manifest.*.json.
#
# Usage:
#   bash darwin/scripts/sgplayer/generate_package_swift.sh ios|macos

set -euo pipefail

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "${SCRIPT_DIR}/_common.sh"
kinetic_sgplayer_init "${1:-}"

PACKAGE_SWIFT="${PLATFORM_DIR}/kinetic_player/Package.swift"

if [[ ! -f "${MANIFEST}" ]]; then
  sgplayer_fail "Missing ${MANIFEST}"
fi

python3 - "${KINETIC_SGPLAYER_PLATFORM}" "${MANIFEST}" "${PACKAGE_SWIFT}" <<'PY'
import json
import pathlib
import sys

platform, manifest_path_s, package_path_s = sys.argv[1], sys.argv[2], sys.argv[3]
manifest_path = pathlib.Path(manifest_path_s)
package_path = pathlib.Path(package_path_s)
data = json.loads(manifest_path.read_text(encoding="utf-8"))

url = (data.get("download_url") or "").strip()
sha = (data.get("sha256") or "").strip().lower()
if sha.startswith("sha256:"):
    sha = sha[len("sha256:") :]

generator = "darwin/scripts/sgplayer/generate_package_swift.sh"
manifest_rel = f"darwin/sgplayer/manifest.{platform}.json"

if platform == "ios":
    if not url:
        raise SystemExit("download_url is empty in darwin/sgplayer/manifest.ios.json")
    if not sha or len(sha) != 64:
        raise SystemExit("sha256 must be a 64-char hex digest in darwin/sgplayer/manifest.ios.json")
    sgplayer_target = f'''        .binaryTarget(
            name: "SGPlayer",
            url: "{url}",
            checksum: "{sha}"
        ),'''
    platforms_line = "        .iOS(.v13),"
    flutter_path = "../FlutterFramework"
elif platform == "macos":
    if url and sha and len(sha) == 64:
        sgplayer_target = f'''        .binaryTarget(
            name: "SGPlayer",
            url: "{url}",
            checksum: "{sha}"
        ),'''
    elif not url:
        sgplayer_target = '''        .binaryTarget(
            name: "SGPlayer",
            path: "../../darwin/Frameworks/macos/SGPlayer.xcframework"
        ),'''
    else:
        raise SystemExit("download_url set but sha256 missing or invalid in manifest")
    platforms_line = "        .macOS(.v11),"
    flutter_path = "../FlutterFramework"
else:
    raise SystemExit(f"unsupported platform: {platform}")

content = f'''// swift-tools-version: 5.9
//
// Generated by {generator} — do not edit by hand.
// Source of truth: {manifest_rel}

import PackageDescription

let package = Package(
    name: "kinetic_player",
    platforms: [
{platforms_line}
    ],
    products: [
        .library(name: "kinetic-player", targets: ["kinetic_player"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "{flutter_path}"),
    ],
    targets: [
{sgplayer_target}
        .target(
            name: "SgNativePlayerBridge",
            dependencies: ["SGPlayer"],
            path: "../../../darwin/SgNativePlayerBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedLibrary("iconv"),
                .linkedLibrary("bz2"),
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "SgPlayerKit",
            dependencies: ["SgNativePlayerBridge"],
            path: "../../../darwin/kinetic_player/Sources/SgPlayerKit"
        ),
        .target(
            name: "kinetic_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "SgPlayerKit",
            ],
            path: "Sources/kinetic_player"
        ),
    ]
)
'''

package_path.write_text(content, encoding="utf-8")
print(f"[generate_package_swift] Wrote {package_path}")
if platform == "ios":
    print(f"[generate_package_swift] url={url}")
    print(f"[generate_package_swift] checksum={sha}")
PY
