#!/usr/bin/env bash
#
# Regenerate ios/kinetic_player/Package.swift from sgplayer_binary_manifest.json.
# Uses remote binaryTarget(url:checksum:) so SPM can auto-download SGPlayer.
#
# Usage:
#   bash ios/scripts/generate_package_swift.sh

set -euo pipefail

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IOS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MANIFEST="${IOS_DIR}/sgplayer_binary_manifest.json"
PACKAGE_SWIFT="${IOS_DIR}/kinetic_player/Package.swift"

if [[ ! -f "${MANIFEST}" ]]; then
  echo "[generate_package_swift] Missing ${MANIFEST}" >&2
  exit 1
fi

python3 - "${MANIFEST}" "${PACKAGE_SWIFT}" <<'PY'
import json
import pathlib
import sys

manifest_path = pathlib.Path(sys.argv[1])
package_path = pathlib.Path(sys.argv[2])
data = json.loads(manifest_path.read_text(encoding="utf-8"))

url = (data.get("download_url") or "").strip()
sha = (data.get("sha256") or "").strip().lower()
if sha.startswith("sha256:"):
    sha = sha[len("sha256:") :]

if not url:
    raise SystemExit("download_url is empty in sgplayer_binary_manifest.json")
if not sha or len(sha) != 64:
    raise SystemExit("sha256 must be a 64-char hex digest in sgplayer_binary_manifest.json")

content = f'''// swift-tools-version: 5.9
//
// Generated by ios/scripts/generate_package_swift.sh — do not edit by hand.
// Source of truth: ios/sgplayer_binary_manifest.json
// Re-run after updating download_url / sha256 (also called by package_sgplayer_release.sh).

import PackageDescription

let package = Package(
    name: "kinetic_player",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(name: "kinetic-player", targets: ["kinetic_player"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .binaryTarget(
            name: "SGPlayer",
            url: "{url}",
            checksum: "{sha}"
        ),
        .target(
            name: "SgNativePlayerBridge",
            dependencies: ["SGPlayer"],
            path: "Sources/SgNativePlayerBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedLibrary("iconv"),
                .linkedLibrary("bz2"),
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "kinetic_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "SgNativePlayerBridge",
            ],
            path: "Sources/kinetic_player"
        ),
    ]
)
'''

package_path.write_text(content, encoding="utf-8")
print(f"[generate_package_swift] Wrote {package_path}")
print(f"[generate_package_swift] url={url}")
print(f"[generate_package_swift] checksum={sha}")
PY
