// swift-tools-version: 5.9
//
// Generated by darwin/scripts/sgplayer/generate_package_swift.sh — do not edit by hand.
// Source of truth: darwin/sgplayer/manifest.macos.json

import PackageDescription

let package = Package(
    name: "kinetic_player",
    platforms: [
        .macOS(.v11),
    ],
    products: [
        .library(name: "kinetic-player", targets: ["kinetic_player"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .binaryTarget(
            name: "SGPlayer",
            path: "../../darwin/Frameworks/macos/SGPlayer.xcframework"
        ),
        .target(
            name: "SgNativePlayerBridge",
            dependencies: ["SGPlayer"],
            path: "../../../darwin/SgNativePlayerBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedLibrary("iconv"),
                .linkedLibrary("bz2"),
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "SgPlayerKit",
            dependencies: ["SgNativePlayerBridge"],
            path: "../../../darwin/kinetic_player/Sources/SgPlayerKit"
        ),
        .target(
            name: "kinetic_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "SgPlayerKit",
            ],
            path: "Sources/kinetic_player"
        ),
    ]
)
