// swift-tools-version: 5.9
//
// Generated by darwin/scripts/sgplayer/generate_package_swift.sh — do not edit by hand.
// Source of truth: darwin/sgplayer/manifest.ios.json

import PackageDescription

let package = Package(
    name: "kinetic_player",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(name: "kinetic-player", targets: ["kinetic_player"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework"),
    ],
    targets: [
        .binaryTarget(
            name: "SGPlayer",
            url: "https://github.com/wanwenfeng4798/kinetic_player/releases/download/sgplayer-v1.0.0/SGPlayer.xcframework.zip",
            checksum: "200809e52688fde99a64e3f8c5b6bd2602311dc5968f329cb9db606305413f84"
        ),
        .target(
            name: "SgNativePlayerBridge",
            dependencies: ["SGPlayer"],
            path: "../../../darwin/SgNativePlayerBridge",
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("include"),
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("VideoToolbox"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedLibrary("iconv"),
                .linkedLibrary("bz2"),
                .linkedLibrary("z"),
            ]
        ),
        .target(
            name: "SgPlayerKit",
            dependencies: ["SgNativePlayerBridge"],
            path: "../../../darwin/kinetic_player/Sources/SgPlayerKit"
        ),
        .target(
            name: "kinetic_player",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework"),
                "SgPlayerKit",
            ],
            path: "Sources/kinetic_player"
        ),
    ]
)
